output_dir: "./outputs"
columns:
- avg_price
- timestamp
- ESP
- ROE

stock_symbols:
- VOO
- VGT
- QQQ
# - NVDA
# - META
# - NFLX
# - MSFT
# - AMZN
# - AVGO
# - TSLA
# - GOOGL
# - GOOG
# - COST
# - PEP
# - CSCO
# - QCOM
# - ADBE
# - INTC

stock_start_date: 2020-01-01
stock_end_date: 2025-01-01
# stock_api: yfinance
sampling_start_date: 2020-01-01
sampling_end_date: 2025-01-01
history_window_size: 360
future_window_size: 180
agg_windows_size: 30
train_batch_size: 32
num_workers: 16
lr: 1e-2
weight_decay: 1e-6
optimizer: sgd
max_num_iters: 100000