output_dir: "./outputs"
columns:
- avg_price

stock_symbols:
- QQQ
# - VOO

stock_start_date: 2020-01-01
stock_end_date: 2025-09-25

simple_forecast_history_start_date: 2024-09-25
simple_forecast_history_end_date: 2025-09-25


train_buy_strategy:
  num_workers: 8
  device: cpu
  simulation_T: 12
  simulate_time_interval: 30
  simulation_batch_size: 4096
  buy_strategy_a_from: 0.0
  buy_strategy_a_to: 2.0
  buy_strategy_b_from: 0.0
  buy_strategy_b_to: 1.0
  buy_strategy_c_from: 0.0
  buy_strategy_c_to: 2.0
  buy_strategy_alpha: 0.5
  pred_std_multiplier: 1.5
  grid_size: 10
