output_dir: "./outputs"
columns:
- avg_price
- EPS


etf_symbols:
- QQQ
# - VGT
# - QQQ

stock_symbols:
- NVDA
- META
- NFLX
- MSFT
- AMZN
- AVGO
- TSLA
- GOOGL
- GOOG
- COST
- PEP
- CSCO
- QCOM
# - ADBE
# - INTC

stock_start_date: 2020-01-01
stock_end_date: 2025-09-25
# stock_api: yfinance
sampling_start_date: 2020-01-01
sampling_end_date: 2025-01-01
history_window_size: 360
future_window_size: 180
agg_windows_size: 30
train_batch_size: 1024
num_workers: 8
lr: 1e-3
weight_decay: 1e-6
optimizer: sgd
max_num_iters: 100000
loss_avg_decay: 0.99
simulate_time_interval: 30
simulation_batch_size: 2048
simulation_T: 6
batch_gain_alpha: 0.5
log_interval: 1000
train_buy_strategy:
  overbuy_penalty_factor: 10.0
  sell_penalty_factor: 10.0
  lr: 1e-8
  weight_decay: 1e-4
  optimizer: sgd
  max_num_iters: 1000000
  loss_avg_decay: 0.99
  batch_gain_alpha: 0.5
